[server]
headless = true
enableCORS = false
port = 8000

[theme]
base = "dark"
primaryColor = "#2EC4F1"
backgroundColor = "#0F1626"
secondaryBackgroundColor = "#1C2331"
textColor = "#F0F4F8"
font = "sans serif"

