name: Verificar Streamlit App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-streamlit:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r projeto/requirements.txt

    - name: Testar importação do app Streamlit
      run: |
        python -m py_compile projeto/streamlit/streamlit.py
